In [1]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Loading Data
df = pd.read_csv('golf_weather_dataset.csv')
df

    Unnamed: 0   Outlook Temperature Humidity  Windy Play
0            0     sunny         hot     high  False   no
1            1     sunny         hot     high   True   no
2            2  overcast         hot     high  False  yes
3            3     rainy        mild     high  False  yes
4            4     rainy        cool   normal  False  yes
5            5     rainy        cool   normal   True   no
6            6  overcast        cool   normal   True  yes
7            7     sunny        mild     high  False   no
8            8     sunny        cool   normal  False  yes
9            9     rainy        mild   normal  False  yes
10          10     sunny        mild   normal   True  yes
11          11  overcast        mild     high   True  yes
12          12  overcast         hot   normal  False  yes
13          13     rainy        mild     high   True   no

In [3]:
# Data Preprocessing
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   14 non-null     int64
 1   Outlook      14 non-null     object
 2   Temperature  14 non-null     object
 3   Humidity     14 non-null     object
 4   Windy        14 non-null     bool
 5   Play         14 non-null     object
dtypes: bool(1), int64(1), object(4)
memory usage: 702.0+ bytes

In [4]:
df.describe(include='all')

        Unnamed: 0 Outlook Temperature Humidity  Windy Play
count      14.0000      14          14       14     14   14
unique         NaN       3           3        2      2    2
top            NaN   sunny        mild     high  False  yes
freq           NaN       5           6        7      8    9
mean        6.5000     NaN         NaN      NaN    NaN  NaN
std         4.1833     NaN         NaN      NaN    NaN  NaN
min         0.0000     NaN         NaN      NaN    NaN  NaN
25%         3.2500     NaN         NaN      NaN    NaN  NaN
50%         6.5000     NaN         NaN      NaN    NaN  NaN
75%         9.7500     NaN         NaN      NaN    NaN  NaN
max        13.0000     NaN         NaN      NaN    NaN  NaN

In [5]:
df.head()

   Unnamed: 0   Outlook Temperature Humidity  Windy Play
0           0     sunny         hot     high  False   no
1           1     sunny         hot     high   True   no
2           2  overcast         hot     high  False  yes
3           3     rainy        mild     high  False  yes
4           4     rainy        cool   normal  False  yes

In [6]:
# Drop the unnamed column
df_1 = df.drop(['Unnamed: 0'], axis=1)

In [7]:
df_1

     Outlook Temperature Humidity  Windy Play
0      sunny         hot     high  False   no
1      sunny         hot     high   True   no
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
5      rainy        cool   normal   True   no
6   overcast        cool   normal   True  yes
7      sunny        mild     high  False   no
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no

In [8]:
# Create dummies for categorical variables except Play
y = df_1['Play']
x = df_1.drop(['Play'], axis=1)

In [9]:
print(y)
print(x)

0      no
1      no
2     yes
3     yes
4     yes
5      no
6     yes
7      no
8     yes
9     yes
10    yes
11    yes
12    yes
13     no
Name: Play, dtype: object
     Outlook Temperature Humidity  Windy
0      sunny         hot     high  False
1      sunny         hot     high   True
2   overcast         hot     high  False
3      rainy        mild     high  False
4      rainy        cool   normal  False
5      rainy        cool   normal   True
6   overcast        cool   normal   True
7      sunny        mild     high  False
8      sunny        cool   normal  False
9      rainy        mild   normal  False
10     sunny        mild   normal   True
11  overcast        mild     high   True
12  overcast         hot   normal  False
13     rainy        mild     high   True

In [18]:
x_dummies_vals = pd.get_dummies(x, columns=[['Windy', 'Humidity', 'Temperature', 'Outlook']])
x_dummies_vals

KeyError: "None of [Index([('Windy', 'Humidity', 'Temperature', 'Outlook')], dtype='object')] are in the [columns]"

In [11]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

x_train, x_test, y_trian, y_test = train_test_split(x_dummies_vals, y, test_size=0.2)

In [12]:
tree_obj = DecisionTreeClassifier()
model = tree_obj.fit(x_train, y_trian)

In [14]:
# Predict

y_hat  = model.predict(x_test)

In [17]:
# Model Accuracy
from sklearn import metrics
print("Accuracy:", metrics.accuracy_score(x_test, y_test))

ValueError: Classification metrics can't handle a mix of unknown and binary targets